# Generated by Django 3.2.25 on 2024-10-06 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicomViewer', '0003_alter_dicomfile_dicom_file_alter_dicomfile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
