# Generated by Django 5.1.1 on 2024-11-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicomViewer', '0005_alter_dicomfile_dicom_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dicomfile',
            name='estudio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dicom_images', to='dicomViewer.estudio'),
            preserve_default=False,
        ),
    ]
